=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-finance-library/2.0.4/jsonSchemas/InvoiceLineSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/InvoiceLine",
  "definitions": {
    "InvoiceLine": {
      "description": "A product or service appearing on an invoice, along with any charges for them",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "id",
        "name",
        "invoiceLineType"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "Unique identifier for the entity, can be null on create if auto-generated"
        },
        "name": {
          "type": "string",
          "description": "Short name of the invoice line item"
        },
        "description": {
          "type": "string",
          "description": "Longer description of the invoice line item"
        },
        "lineNumber": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "description": "Line number of the invoice item"
        },
        "invoiceLineType": {
          "type": "string",
          "description": "Indicates the type of invoice line, such as Charge or Rebate"
        },
        "invoiceLineStatus": {
          "type": "string",
          "description": "Current status of the invoice line item"
        },
        "fulfillmentOrderProductId": {
          "type": "string",
          "description": "References the fulfillment order product the invoice line item is for"
        },
        "salesOrderProductId": {
          "type": "string",
          "description": "References the sales order product the invoice line item is for"
        },
        "productId": {
          "type": "string",
          "description": "References the underlying product associated with the sales order product"
        },
        "productCode": {
          "type": "string",
          "description": "Code of the underlying product associated with the sales order product"
        },
        "lineStartDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ],
          "description": "Start date for the invoice line item"
        },
        "lineEndDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ],
          "description": "End date for the invoice line item"
        },
        "lineQuantity": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ]
        },
        "unitPrice": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "description": "What the customer is paying for one unit of the product"
        },
        "grossUnitPrice": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "description": "Unit price including tax"
        },
        "totalAdjustmentAmount": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "description": "Total adjustments, not including tax, of the invoice line item"
        },
        "totalAdjustmentTaxAmount": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "description": "Tax on the total adjustment amount"
        },
        "totalAdjustmentWithTaxAmount": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "description": "Sum of totalAdjustmentAmount + totalAdjustmentTaxAmount"
        },
        "totalChargeAmount": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "description": "Total amount of charges, not including tax, of the invoice line item"
        },
        "totalChargeTaxAmount": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "description": "Tax on the total charge amount"
        },
        "totalChargeWithTaxAmount": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "description": "Sum of totalChargeAmount + totalChargeTaxAmount"
        },
        "totalAmount": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "description": "Adjusted total, not including tax, of the invoice line item"
        },
        "totalTaxAmount": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "description": "Sum of all tax amounts for the invoice line item"
        },
        "totalWithTaxAmount": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "description": "Sum of totalAmount + totalTaxAmount"
        },
        "taxCode": {
          "type": "string",
          "description": "Identifies the reason for the tax calculation"
        },
        "taxName": {
          "type": "string",
          "description": "Display name for the tax applied"
        },
        "taxRatePercent": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "description": "Percentage rate of tax applied"
        },
        "taxEffectiveDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ],
          "description": "Date used to calculate the effective tax rate"
        },
        "auditInfo": {
          "type": "object",
          "description": "Audit information for the entity",
          "additionalProperties": true,
          "required": [
            "createdBy",
            "isDeleted",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-finance-library/2.0.4/examples/InvoiceLineExample.json
{
  "id": "337d5e99-287f-4f68-ac95-ed435d7c5797",
  "name": "Standard Merchandise",
  "description": "",
  "lineNumber": 1,
  "invoiceLineType": "Charge",
  "invoiceLineStatus": "Unpaid",
  "salesOrderProductId": "c5fab4e7-f942-415b-8f26-4cbd7104e3ac",
  "fulfillmentOrderProductId": "12ea2ef0-665f-4d96-95f8-6b64fe2f480e",
  "productId": "2ff88028-754b-4ce9-a7e0-4be47c7a1476",
  "productCode": "StdMerch",
  "lineStartDate": "2024-03-01",
  "lineEndDate": null,
  "lineQuantity": 2,
  "unitPrice": 24.50,
  "grossUnitPrice": 26.95,
  "totalAdjustmentAmount": 0.0,
  "totalAdjustmentTaxAmount": 0.0,
  "totalAdjustmentWithTaxAmount": 0.0,
  "totalChargeAmount": 49.0,
  "totalChargeTaxAmount": 4.9,
  "totalChargeWithTaxAmount": 53.9,
  "totalAmount": 49.0,
  "totalTaxAmount": 4.9,
  "totalWithTaxAmount": 53.9,
  "taxCode": "HST",
  "taxName": "Harmonized Sales Tax",
  "taxRatePercent": 10.0,
  "taxEffectiveDate": null,
  "auditInfo": {
    "createdDate": "2023-04-30T17:25:11.128Z",
    "createdBy": "Application Admin",
    "updatedDate": "2023-04-30T17:25:11.128Z",
    "updatedBy": "Application Admin",
    "isDeleted": false
  }
}
