=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-finance-library/2.0.4/jsonSchemas/PaymentGatewaySchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/PaymentGateway",
  "definitions": {
    "PaymentGateway": {
      "description": "Holds the payment gateway merchant details, which are used to interact external payment systems",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "id",
        "name",
        "paymentGatewayStatus"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "Unique identifier for the entity, can be null on create if auto-generated"
        },
        "name": {
          "type": "string",
          "description": "Short name of the payment gateway"
        },
        "paymentGatewayStatus": {
          "type": "string",
          "description": "Current status of the payment gateway, such as Active or Inactive"
        },
        "paymentGatewayProvider": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "description": "Provides details about the underlying payment gateway provider",
              "type": "object",
              "additionalProperties": true,
              "required": [
                "id",
                "name"
              ],
              "properties": {
                "id": {
                  "anyOf": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "null"
                    }
                  ],
                  "description": "Unique identifier for the entity, can be null on create if auto-generated"
                },
                "name": {
                  "type": "string",
                  "description": "Short name for the payment gateway provider"
                },
                "namespacePrefixText": {
                  "type": "string",
                  "description": "Qualifier used to provide uniqueness to the payment gateway provider name"
                },
                "implementationClassName": {
                  "type": "string",
                  "description": "Programmatic name of the class that implements the payment gateway provider"
                },
                "developerName": {
                  "type": "string",
                  "description": "Name used within program code to identify the payment gateway provider"
                },
                "commentText": {
                  "type": "string",
                  "description": "Descriptive text about the payment gateway provider"
                },
                "auditInfo": {
                  "type": "object",
                  "description": "Audit information for the entity",
                  "additionalProperties": true,
                  "required": [
                    "createdBy",
                    "isDeleted",
                    "updatedBy",
                    "updatedDate",
                    "createdDate"
                  ],
                  "properties": {
                    "createdDate": {
                      "anyOf": [
                        {
                          "type": "string",
                          "format": "date-time"
                        },
                        {
                          "type": "null"
                        }
                      ],
                      "description": "Timestamp of when the entity was created"
                    },
                    "createdBy": {
                      "type": "string",
                      "description": "Identifies the system or user which created the entity"
                    },
                    "updatedDate": {
                      "anyOf": [
                        {
                          "type": "string",
                          "format": "date-time"
                        },
                        {
                          "type": "null"
                        }
                      ],
                      "description": "Timestamp of when the entity was last updated"
                    },
                    "updatedBy": {
                      "type": "string",
                      "description": "Identifies the system or user which last updated the entity"
                    },
                    "isDeleted": {
                      "anyOf": [
                        {
                          "type": "boolean"
                        },
                        {
                          "type": "null"
                        }
                      ],
                      "description": "Indicates whether or not the entity has been soft-deleted"
                    }
                  }
                }
              }
            }
          ],
          "description": "References the actual provider for the payment gateway"
        },
        "systemCredentialId": {
          "type": "string",
          "description": "References the credentials used for authentication with the payment gateway"
        },
        "commentText": {
          "type": "string",
          "description": "Descriptive text about the payment gateway"
        },
        "auditInfo": {
          "type": "object",
          "description": "Audit information for the entity",
          "additionalProperties": true,
          "required": [
            "createdBy",
            "isDeleted",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-finance-library/2.0.4/examples/PaymentGatewayExample.json
{
  "id": "6faa21ba-5a97-445b-afaa-4d866f0388f5",
  "name": "Internal gateway",
  "paymentGatewayStatus": "Active",
  "paymentGatewayProvider": "Fundy",
  "systemCredentialId": "ece670c0-f099-4f4d-9538-6fd855922dc6",
  "commentText": "Implemented via Moneris Adapter Class",
  "auditInfo": {
    "createdDate": "2021-04-21T01:12:28.801Z",
    "createdBy": "Application Admin",
    "updatedDate": "2021-04-21T01:12:28.801Z",
    "updatedBy": "Application Admin",
    "isDeleted": false
  }
}
