=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-finance-library/2.0.4/jsonSchemas/PaymentGatewayInteractionLogSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/PaymentGatewayInteractionLog",
  "definitions": {
    "PaymentGatewayInteractionLog": {
      "description": "A record of all messages exchanged with merchants, made via the payment gateway, for authorizations and payments",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "id",
        "paymentGatewayInteractionType",
        "referencedEntityId",
        "paymentGatewayInteractionStatus",
        "paymentGatewayDateTime",
        "paymentGatewayResultCode"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "Unique identifier for the entity, can be null on create if auto-generated"
        },
        "name": {
          "type": "string",
          "description": "Short name of the payment gateway interaction log entry"
        },
        "paymentGatewayInteractionType": {
          "type": "string",
          "description": "Type of interaction with the gateway for the log entry, such as a CardPayment or RefundPayment"
        },
        "referencedEntityId": {
          "type": "string",
          "description": "References the primary entity involved in the interaction, such as a CardPayment or RefundPayment"
        },
        "paymentGatewayInteractionStatus": {
          "type": "string",
          "description": "Status of the interaction, such as Success or Timeout"
        },
        "paymentGatewayDateTime": {
          "type": "string",
          "description": "Datetime provided by the gateway after successful communication",
          "format": "date-time"
        },
        "paymentGatewayReferenceNumber": {
          "type": "string",
          "description": "Unique transaction identifier generated by payment gateway"
        },
        "paymentGatewayAuthorizationCode": {
          "type": "string",
          "description": "Authorization approval code sent back by the gateway"
        },
        "paymentGatewayResultCode": {
          "type": "string",
          "description": "Result code returned by the gateway"
        },
        "paymentGatewayAvsCode": {
          "type": "string",
          "description": "Unique code assigned by the gateway for address verification"
        },
        "paymentGatewayInternalReferenceNumber": {
          "type": "string",
          "description": "Unique transaction identifier generated by the internal payment platform"
        },
        "paymentGatewayInternalResultCode": {
          "type": "string",
          "description": "Internal result code returned by the internal payment platform"
        },
        "paymentGatewayMessageText": {
          "type": "string",
          "description": "Message sent by the payment gateway"
        },
        "auditInfo": {
          "type": "object",
          "description": "Audit information for the entity",
          "additionalProperties": true,
          "required": [
            "createdBy",
            "isDeleted",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-finance-library/2.0.4/examples/PaymentGatewayInteractionLogExample.json
{
  "id": "ee315481-1665-463a-8d0d-700ea24d4b87",
  "name": "Authorization attempt",
  "paymentGatewayInteractionType": "Auth",
  "referencedEntityId": "1de8ed0e-02ad-11ed-b939-0242ac120002",
  "paymentGatewayInteractionStatus": "Success",
  "paymentGatewayDateTime": "2023-04-21T01:13:12.924Z",
  "paymentGatewayReferenceNumber": "8B566A5B-8C2F-47E7-A4EC-18C26001ADEA",
  "paymentGatewayAuthorizationCode": "542845",
  "paymentGatewayResultCode": "100",
  "paymentGatewayAvsCode": "",
  "paymentGatewayInternalReferenceNumber": "",
  "paymentGatewayInternalResultCode": "",
  "paymentGatewayMessageText": "No errors",
  "auditInfo": {
    "createdDate": "2021-04-21T01:12:28.801Z",
    "createdBy": "Application Admin",
    "updatedDate": "2021-04-21T01:12:28.801Z",
    "updatedBy": "Application Admin",
    "isDeleted": false
  }
}
