=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-finance-library/2.0.4/jsonSchemas/PaymentAuthorizationReversalSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/PaymentAuthorizationReversal",
  "definitions": {
    "PaymentAuthorizationReversal": {
      "description": "An authorization reversal alerts the issuer that part or all of a sale has been cancelled and the authorization hold should be rescinded",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "id",
        "paymentAuthorizationReversalStatus",
        "paymentAuthorizationProcessingMode",
        "authorizationReversalAmount",
        "paymentAuthorizationId"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "Unique identifier for the entity, can be null on create if auto-generated"
        },
        "name": {
          "type": "string",
          "description": "Short description of the payment authorization reversal entry"
        },
        "paymentAuthorizationReversalStatus": {
          "type": "string",
          "description": "Processing stage of the payment authorization reversal"
        },
        "paymentAuthorizationProcessingMode": {
          "type": "string",
          "description": "Describes whether the payment processing was done by the platform or by an external system"
        },
        "authorizationReversalAmount": {
          "type": "number",
          "description": "Amount that was previously authorized and is now being reversed"
        },
        "paymentAuthorizationId": {
          "type": "string",
          "description": "References the original payment authorization that is being reversed"
        },
        "capturePaymentId": {
          "type": "string",
          "description": "References the capture payment the refund allocation applies to"
        },
        "customerEmailAddress": {
          "type": "string",
          "description": "Email address that is used in the authorization/reversal process"
        },
        "customerPhoneNumber": {
          "type": "string",
          "description": "Phone number that is used in the authorization/reversal process"
        },
        "gatewayRequestDateTime": {
          "type": "string",
          "description": "Date and time when the payment platform sent the authorization request to the gateway",
          "format": "date-time"
        },
        "paymentGatewayDateTime": {
          "type": "string",
          "description": "Datetime provided by the gateway after successful communication",
          "format": "date-time"
        },
        "paymentGatewayReferenceNumber": {
          "type": "string",
          "description": "Unique transaction identifier generated by payment gateway"
        },
        "paymentGatewayResultCode": {
          "type": "string",
          "description": "Result code returned by the gateway"
        },
        "paymentGatewayInternalReferenceNumber": {
          "type": "string",
          "description": "Unique transaction identifier generated by the internal payment platform"
        },
        "paymentGatewayInternalResultCode": {
          "type": "string",
          "description": "Internal result code returned by the internal payment platform"
        },
        "ipAddress": {
          "type": "string",
          "description": "Unique network address of the device that originated the payment authorization request"
        },
        "macAddress": {
          "type": "string",
          "description": "Unique hardware identification number of the device that originated the payment authorization request"
        },
        "commentText": {
          "type": "string",
          "description": "Descriptive text about the payment authorization reversal"
        },
        "externalCreatedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ],
          "description": "Preserves original creation date for payments imported from external systems"
        },
        "auditInfo": {
          "type": "object",
          "description": "Audit information for the entity",
          "additionalProperties": true,
          "required": [
            "createdBy",
            "isDeleted",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-finance-library/2.0.4/examples/PaymentAuthorizationReversalExample.json
{
  "id": "6faa21ba-5a97-445b-afaa-4d866f0388f5",
  "name": "",
  "paymentAuthorizationReversalStatus": "Completed",
  "paymentAuthorizationProcessingMode": "Internal",
  "authorizationReversalAmount": 261.0,
  "paymentAuthorizationId": "1de8ed0e-02ad-11ed-b939-0242ac120002",
  "capturePaymentId": "cb45464a-dbe0-4b4c-8f7f-445dee3cbaa9",
  "customerEmailAddress": "johnf@example.net",
  "customerPhoneNumber": "888-555-01234",
  "gatewayRequestDateTime": "2023-04-21T01:12:28.801Z",
  "paymentGatewayDateTime": "2023-04-21T01:13:12.924Z",
  "paymentGatewayReferenceNumber": "9B566A5B-8D2F-43E7-B4EF-C3C2600139D0",
  "paymentGatewayResultCode": "200",
  "paymentGatewayInternalReferenceNumber": "",
  "paymentGatewayInternalResultCode": "",
  "ipAddress": "116.161.101.202",
  "macAddress": "68-53-41-11-D3-25",
  "commentText": "Reversed in full",
  "externalCreatedDate": null,
  "auditInfo": {
    "createdDate": "2021-04-21T01:12:28.801Z",
    "createdBy": "Application Admin",
    "updatedDate": "2021-04-21T01:12:28.801Z",
    "updatedBy": "Application Admin",
    "isDeleted": false
  }
}
