=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-finance-library/2.0.4/jsonSchemas/PaymentAllocationSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/PaymentAllocation",
  "definitions": {
    "PaymentAllocation": {
      "description": "A payment application may be further broken down into allocations, to allocate payment funds to one or more line items within an invoice or credit memo",
      "discriminator": "paymentAllocationInstance",
      "discriminatorValue": "PaymentAllocation",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "id",
        "paymentAllocationInstance",
        "appliedAmount"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "Unique identifier for the entity, can be null on create if auto-generated"
        },
        "name": {
          "type": "string",
          "description": "Short description of the payment allocation"
        },
        "paymentAllocationInstance": {
          "type": "string",
          "description": "Discriminator property identifying the specific payment allocation instance type, such as PaymentCreditMemoAllocation"
        },
        "relatedPaymentAllocationId": {
          "type": "string",
          "description": "Relates a new payment allocation back to the original, in cases where payments are unapplied"
        },
        "appliedAmount": {
          "type": "number",
          "description": "Amount of currency of the payment applied to the invoice or credit memo line item"
        },
        "externalCreatedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ],
          "description": "Preserves original creation date for payments imported from external systems"
        },
        "auditInfo": {
          "type": "object",
          "description": "Audit information for the entity",
          "additionalProperties": true,
          "required": [
            "createdBy",
            "isDeleted",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-finance-library/2.0.4/examples/PaymentCreditMemoAllocationExample.json
{
  "id": "5fb7341e-bf4e-4a53-93fd-dc8f36213389",
  "name": "Credit memo allocation",
  "paymentAllocationInstance": "PaymentCreditMemoAllocation",
  "relatedPaymentAllocationId": "",
  "appliedAmount": 636.0,
  "externalCreatedDate": null,
  "auditInfo": {
    "createdDate": "2021-04-21T01:12:28.801Z",
    "createdBy": "Application Admin",
    "updatedDate": "2021-04-21T01:12:28.801Z",
    "updatedBy": "Application Admin",
    "isDeleted": false
  }
}

=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-finance-library/2.0.4/examples/PaymentAllocationExample.json
{
  "id": "5fb7341e-bf4e-4a53-93fd-dc8f36213389",
  "name": "Complete allocation",
  "paymentAllocationInstance": "PaymentAllocation",
  "relatedPaymentAllocationId": "",
  "appliedAmount": 636.0,
  "externalCreatedDate": null,
  "auditInfo": {
    "createdDate": "2021-04-21T01:12:28.801Z",
    "createdBy": "Application Admin",
    "updatedDate": "2021-04-21T01:12:28.801Z",
    "updatedBy": "Application Admin",
    "isDeleted": false
  }
}
