=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-produce-library/2.0.8/jsonSchemas/BrandSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/Brand",
  "definitions": {
    "Brand": {
      "description": "Defines the name, term, design, symbol, and other features that identify one good or service as being distinct from those of other sellers or internal organizations",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "id",
        "name"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "Unique identifier for the entity, can be null on create if auto-generated"
        },
        "name": {
          "type": "string",
          "description": "Name of the brand"
        },
        "brandGrade": {
          "type": "string",
          "description": "Identifies the value of the brand, such as Premium or Value"
        },
        "parentBrandId": {
          "type": "string",
          "description": "References the larger brand that contains the brand"
        },
        "internalOrganizationId": {
          "type": "string",
          "description": "References an internal organization or department within the company"
        },
        "auditInfo": {
          "type": "object",
          "description": "Audit information for the entity",
          "additionalProperties": true,
          "required": [
            "createdBy",
            "isDeleted",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-produce-library/2.0.8/examples/BrandExample.json
{
  "id": "4788a7ec-00ee-11ed-b939-0242ac120002",
  "name": "Atlas",
  "brandGrade": "Premium",
  "parentBrandId": "",
  "internalOrganizationId": "",
  "auditInfo": {
    "createdDate": "2023-12-12T19:24:05Z",
    "createdBy": "Application Admin",
    "updatedDate": "2023-12-12T19:24:05Z",
    "updatedBy": "Application Admin",
    "isDeleted": true
  }
}
