=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-produce-library/2.0.8/jsonSchemas/InventoryReceivedSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/InventoryReceived",
  "definitions": {
    "InventoryReceived": {
      "description": "Represents an incoming delivery of product inventory",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "Unique identifier for the entity, can be null on create if auto-generated"
        },
        "description": {
          "type": "string",
          "description": "Description of the inventory delivery"
        },
        "receiptNumber": {
          "type": "string",
          "description": "Inventory receipt number"
        },
        "inventoryReceivedDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ],
          "description": "Date the inventory was received"
        },
        "postingDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ],
          "description": "Date the inventory was posted for availability"
        },
        "inventoryReceivedProducts": {
          "type": "array",
          "description": "Inventory products included in the inventory received",
          "items": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "description": "An individual product included in the inventory delivery",
                "type": "object",
                "additionalProperties": true,
                "required": [
                  "id",
                  "purchaseOrderId",
                  "purchaseOrderProductId",
                  "receivedQuantity"
                ],
                "properties": {
                  "id": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "description": "Unique identifier for the entity, can be null on create if auto-generated"
                  },
                  "description": {
                    "type": "string",
                    "description": "Description of the inventory product"
                  },
                  "purchaseOrderId": {
                    "type": "string",
                    "description": "References the purchase order the inventory was purchased for"
                  },
                  "purchaseOrderProductId": {
                    "type": "string",
                    "description": "References the product line item from the associated purchase order"
                  },
                  "storageLocation": {
                    "type": "object",
                    "description": "Location where the inventory product will be stored",
                    "additionalProperties": true,
                    "required": [
                      "id"
                    ],
                    "properties": {
                      "id": {
                        "anyOf": [
                          {
                            "type": "string"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Unique identifier for the entity, can be null on create if auto-generated"
                      },
                      "name": {
                        "type": "string",
                        "description": "Display name of the location"
                      },
                      "contactName": {
                        "type": "string",
                        "description": "Name of the person to contact at this location (for receiving shipments, as an example)"
                      },
                      "locationCode": {
                        "type": "string",
                        "description": "Alternate code associated with the location"
                      },
                      "locationType": {
                        "type": "string",
                        "description": "Reference to the type of location (for example, Bulding, Ship, Arena)"
                      },
                      "locationAddress": {
                        "type": "object",
                        "description": "Free-form or structured address of the location",
                        "additionalProperties": true,
                        "required": [
                          "addressLine1"
                        ],
                        "properties": {
                          "name": {
                            "type": "string",
                            "description": "Optional display name for the address"
                          },
                          "addressLine1": {
                            "type": "string",
                            "description": "The first address line can be used by itself for unstructured addresses"
                          },
                          "addressLine2": {
                            "type": "string",
                            "description": "Optional second line of the address"
                          },
                          "addressLine3": {
                            "type": "string",
                            "description": "Optional third line of the address"
                          },
                          "cityName": {
                            "type": "string",
                            "description": "Display name of the city for the address"
                          },
                          "stateProvinceName": {
                            "type": "string",
                            "description": "Display name of the state or province for the address"
                          },
                          "stateProvinceCode": {
                            "type": "string",
                            "description": "The ISO region code for the address"
                          },
                          "countryName": {
                            "type": "string",
                            "description": "Display name of the country for the address"
                          },
                          "countryCode": {
                            "type": "string",
                            "description": "The ISO country code for the address"
                          },
                          "postalCodeText": {
                            "type": "string",
                            "description": "The postal code for the address"
                          },
                          "geoAccuracyCode": {
                            "type": "string",
                            "description": "Provides more information about the latitude and longitude of the address"
                          },
                          "geoLatitude": {
                            "anyOf": [
                              {
                                "type": "number"
                              },
                              {
                                "type": "null"
                              }
                            ],
                            "description": "The latitude of the address"
                          },
                          "geoLongitude": {
                            "anyOf": [
                              {
                                "type": "number"
                              },
                              {
                                "type": "null"
                              }
                            ],
                            "description": "The longitude of the address"
                          }
                        }
                      },
                      "auditInfo": {
                        "type": "object",
                        "description": "Audit information for the entity",
                        "additionalProperties": true,
                        "required": [
                          "isDeleted",
                          "createdBy",
                          "updatedBy",
                          "updatedDate",
                          "createdDate"
                        ],
                        "properties": {
                          "createdDate": {
                            "anyOf": [
                              {
                                "type": "string",
                                "format": "date-time"
                              },
                              {
                                "type": "null"
                              }
                            ],
                            "description": "Timestamp of when the entity was created"
                          },
                          "createdBy": {
                            "type": "string",
                            "description": "Identifies the system or user which created the entity"
                          },
                          "updatedDate": {
                            "anyOf": [
                              {
                                "type": "string",
                                "format": "date-time"
                              },
                              {
                                "type": "null"
                              }
                            ],
                            "description": "Timestamp of when the entity was last updated"
                          },
                          "updatedBy": {
                            "type": "string",
                            "description": "Identifies the system or user which last updated the entity"
                          },
                          "isDeleted": {
                            "anyOf": [
                              {
                                "type": "boolean"
                              },
                              {
                                "type": "null"
                              }
                            ],
                            "description": "Indicates whether or not the entity has been soft-deleted"
                          }
                        }
                      }
                    }
                  },
                  "receivedQuantity": {
                    "anyOf": [
                      {
                        "type": "number"
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "description": "Amount of inventory product received"
                  },
                  "quantityUnitOfMeasure": {
                    "type": "string",
                    "description": "Unit of measure for the quantity received"
                  },
                  "isCompletelyDelivered": {
                    "anyOf": [
                      {
                        "type": "boolean"
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "description": "True if the entire expected quantity has been received, false otherwise"
                  },
                  "auditInfo": {
                    "type": "object",
                    "description": "Audit information for the entity",
                    "additionalProperties": true,
                    "required": [
                      "createdBy",
                      "isDeleted",
                      "updatedBy",
                      "updatedDate",
                      "createdDate"
                    ],
                    "properties": {
                      "createdDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was created"
                      },
                      "createdBy": {
                        "type": "string",
                        "description": "Identifies the system or user which created the entity"
                      },
                      "updatedDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was last updated"
                      },
                      "updatedBy": {
                        "type": "string",
                        "description": "Identifies the system or user which last updated the entity"
                      },
                      "isDeleted": {
                        "anyOf": [
                          {
                            "type": "boolean"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Indicates whether or not the entity has been soft-deleted"
                      }
                    }
                  }
                }
              }
            ]
          }
        },
        "auditInfo": {
          "type": "object",
          "description": "Audit information for the entity",
          "additionalProperties": true,
          "required": [
            "createdBy",
            "isDeleted",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-produce-library/2.0.8/examples/InventoryReceivedExample.json
{
  "id": "37d8a8e6-00ee-11ed-b939-0242ac168882",
  "description": "Adidas shipment for July",
  "receiptNumber": "RT-0065833",
  "inventoryReceivedDate": "2021-12-12",
  "postingDate": "2021-12-14",
  "inventoryReceivedProducts": [
    {
      "id": null,
      "description": "Flat of tennis shoes",
      "purchaseOrderId": "c242e236-1c49-4b8a-897f-955300e1537e",
      "purchaseOrderProductId": "ORD-02338301-1",
      "storageLocation": {
        "id": "f617ddb6-2628-4401-8886-21ce1854ad6e",
        "name": "Customer Address",
        "contactName": "Samuel L. Smith",
        "locationCode": "338",
        "locationAddress": {
          "addressLine1": "2122 Maple Street",
          "addressLine2": "Unit 23",
          "addressLine3": "",
          "cityName": "Austin",
          "stateProvinceCode": "TX",
          "countryCode": "US",
          "postalCodeText": "45145"
        }
      },
      "receivedQuantity": 10.0,
      "quantityUnitOfMeasure": "Box",
      "isCompletelyDelivered": true
    }
  ],
  "auditInfo": {
    "createdDate": "2024-03-05T07:16:23Z",
    "createdBy": "Application Admin",
    "updatedDate": "2024-03-05T07:16:23Z",
    "updatedBy": "Application Admin",
    "isDeleted": false
  }
}
