=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-produce-library/2.0.8/jsonSchemas/ProductCategoryProductSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ProductCategoryProduct",
  "definitions": {
    "ProductCategoryProduct": {
      "description": "Assignment of a product to a category, such as a specific shoe assigned to shoe and running categories",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "id",
        "productId",
        "activeFromDate"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "Unique identifier for the entity, can be null on create if auto-generated"
        },
        "productId": {
          "type": "string",
          "description": "References the product assigned to the category"
        },
        "activeFromDate": {
          "type": "string",
          "description": "Date from when the product is active in the category",
          "format": "date"
        },
        "activeToDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ],
          "description": "Date to when the product is active in the category"
        },
        "auditInfo": {
          "type": "object",
          "description": "Audit information for the entity",
          "additionalProperties": true,
          "required": [
            "createdBy",
            "isDeleted",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-produce-library/2.0.8/examples/ProductCategoryProductExample.json
{
  "id": "6fbe94a3-a6a8-4c53-9d23-08fa54fd316b",
  "productId": "87a8234e-bbf3-46ed-a94e-a128b959be07",
  "activeFromDate": "2021-12-12",
  "activeToDate": null,
  "auditInfo": {
    "createdDate": "2023-12-12T19:24:05Z",
    "createdBy": "Application Admin",
    "updatedDate": "2023-12-12T19:24:05Z",
    "updatedBy": "Application Admin",
    "isDeleted": true
  }
}
