=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-produce-library/2.0.8/jsonSchemas/ProductRelationshipTypeSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ProductRelationshipType",
  "definitions": {
    "ProductRelationshipType": {
      "description": "Defines the types of relationships available, such as bundled with or substituted for",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "id",
        "parentProductRole",
        "childProductRole"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "Unique identifier for the entity, can be null on create if auto-generated"
        },
        "name": {
          "type": "string",
          "description": "Name of the product relationship type"
        },
        "parentProductRole": {
          "type": "string",
          "description": "What is the first role in the relationship, such as Consists of"
        },
        "childProductRole": {
          "type": "string",
          "description": "What is the second role in the relationship, such as Component of"
        },
        "auditInfo": {
          "type": "object",
          "description": "Audit information for the entity",
          "additionalProperties": true,
          "required": [
            "createdBy",
            "isDeleted",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-produce-library/2.0.8/examples/ProductRelationshipTypeExample.json
{
  "id": "2119b3b7-921e-48d9-94b9-f6a2e598ebdc",
  "name": "",
  "parentProductRole": "Collection",
  "childProductRole": "Item",
  "auditInfo": {
    "createdDate": "2023-12-12T19:24:05Z",
    "createdBy": "Application Admin",
    "updatedDate": "2023-12-12T19:24:05Z",
    "updatedBy": "Application Admin",
    "isDeleted": true
  }
}
