=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-produce-library/2.0.8/jsonSchemas/ProductRelatedProductSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ProductRelatedProduct",
  "definitions": {
    "ProductRelatedProduct": {
      "description": "A grouping of products such as a product bundle",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "id",
        "name",
        "productRelationshipType",
        "activeFromDate"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "Unique identifier for the entity, can be null on create if auto-generated"
        },
        "name": {
          "type": "string",
          "description": "Auto-generated name for the relationship"
        },
        "productRelationshipType": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "description": "Defines the types of relationships available, such as bundled with or substituted for",
              "type": "object",
              "additionalProperties": true,
              "required": [
                "id",
                "parentProductRole",
                "childProductRole"
              ],
              "properties": {
                "id": {
                  "anyOf": [
                    {
                      "type": "string"
                    },
                    {
                      "type": "null"
                    }
                  ],
                  "description": "Unique identifier for the entity, can be null on create if auto-generated"
                },
                "name": {
                  "type": "string",
                  "description": "Name of the product relationship type"
                },
                "parentProductRole": {
                  "type": "string",
                  "description": "What is the first role in the relationship, such as Consists of"
                },
                "childProductRole": {
                  "type": "string",
                  "description": "What is the second role in the relationship, such as Component of"
                },
                "auditInfo": {
                  "type": "object",
                  "description": "Audit information for the entity",
                  "additionalProperties": true,
                  "required": [
                    "createdBy",
                    "isDeleted",
                    "updatedBy",
                    "updatedDate",
                    "createdDate"
                  ],
                  "properties": {
                    "createdDate": {
                      "anyOf": [
                        {
                          "type": "string",
                          "format": "date-time"
                        },
                        {
                          "type": "null"
                        }
                      ],
                      "description": "Timestamp of when the entity was created"
                    },
                    "createdBy": {
                      "type": "string",
                      "description": "Identifies the system or user which created the entity"
                    },
                    "updatedDate": {
                      "anyOf": [
                        {
                          "type": "string",
                          "format": "date-time"
                        },
                        {
                          "type": "null"
                        }
                      ],
                      "description": "Timestamp of when the entity was last updated"
                    },
                    "updatedBy": {
                      "type": "string",
                      "description": "Identifies the system or user which last updated the entity"
                    },
                    "isDeleted": {
                      "anyOf": [
                        {
                          "type": "boolean"
                        },
                        {
                          "type": "null"
                        }
                      ],
                      "description": "Indicates whether or not the entity has been soft-deleted"
                    }
                  }
                }
              }
            }
          ],
          "description": "Descripts the type of relationship between the products"
        },
        "parentProductId": {
          "type": "string",
          "description": "Reference to product 1 that is related to product 2"
        },
        "childProductId": {
          "type": "string",
          "description": "Reference to product 2 that is related to product 1"
        },
        "activeFromDate": {
          "type": "string",
          "description": "Date from when the product relationship is active",
          "format": "date"
        },
        "activeToDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ],
          "description": "Date to when the product relationship is active"
        },
        "isDefaultOption": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ],
          "description": "True if this is the default option for a product, such as a phone case being a default option for a phone"
        },
        "auditInfo": {
          "type": "object",
          "description": "Audit information for the entity",
          "additionalProperties": true,
          "required": [
            "createdBy",
            "isDeleted",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-produce-library/2.0.8/examples/ProductRelatedProductExample.json
{
  "id": "e7e85b6b-3d6d-412f-9a94-b78a9b351513",
  "name": "Related product",
  "productRelationshipType": "2119b3b7-921e-48d9-94b9-f6a2e598ebdc",
  "parentProductId": "32c72b39-14cf-41f4-84d1-bd3b3ae73133",
  "childProductId": "af3894f9-5393-4204-a769-a583f5e629f6",
  "activeFromDate": "2022-07-26",
  "activeToDate": null,
  "isDefaultOption": false,
  "auditInfo": {
    "createdDate": "2023-12-12T19:24:05Z",
    "createdBy": "Application Admin",
    "updatedDate": "2023-12-12T19:24:05Z",
    "updatedBy": "Application Admin",
    "isDeleted": true
  }
}
