=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-produce-library/2.0.8/jsonSchemas/ProductCatalogSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ProductCatalog",
  "definitions": {
    "ProductCatalog": {
      "description": "A catalog used for a certain business process, such as inventory or merchandising",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "id",
        "name",
        "activeFromDate"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "Unique identifier for the entity, can be null on create if auto-generated"
        },
        "name": {
          "type": "string",
          "description": "Name of the product catalog"
        },
        "activeFromDate": {
          "type": "string",
          "description": "Date from when the catalog is available for use",
          "format": "date"
        },
        "activeToDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ],
          "description": "Date to when the catalog is available for use"
        },
        "productCategories": {
          "type": "array",
          "description": "List of product categories for the product catelog, which can be a list of identifier references or complete objects (not both)",
          "items": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "description": "A specific category of product in a catalog, such as shoes or shirts",
                "type": "object",
                "additionalProperties": true,
                "required": [
                  "id",
                  "name",
                  "activeFromDate"
                ],
                "properties": {
                  "id": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "description": "Unique identifier for the entity, can be null on create if auto-generated"
                  },
                  "name": {
                    "type": "string",
                    "description": "Name of the product category"
                  },
                  "description": {
                    "type": "string",
                    "description": "Longer description of the product category"
                  },
                  "activeFromDate": {
                    "type": "string",
                    "description": "Date from when the category is active",
                    "format": "date"
                  },
                  "activeToDate": {
                    "anyOf": [
                      {
                        "type": "string",
                        "format": "date"
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "description": "Date to when the category is active"
                  },
                  "productCatalogId": {
                    "type": "string",
                    "description": "Product catalog this category belongs to"
                  },
                  "parentCategoryId": {
                    "type": "string",
                    "description": "An optional reference to a parent category, such as a mobile phone being part of a phone category"
                  },
                  "isNavigational": {
                    "anyOf": [
                      {
                        "type": "boolean"
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "description": "True if the category can be used to locate a product, false otherwise"
                  },
                  "productCategoryProducts": {
                    "type": "array",
                    "description": "List of products included in the category, which can be a list of identifier references or complete objects (not both)",
                    "items": {
                      "anyOf": [
                        {
                          "type": "string"
                        },
                        {
                          "description": "Assignment of a product to a category, such as a specific shoe assigned to shoe and running categories",
                          "type": "object",
                          "additionalProperties": true,
                          "required": [
                            "id",
                            "productId",
                            "activeFromDate"
                          ],
                          "properties": {
                            "id": {
                              "anyOf": [
                                {
                                  "type": "string"
                                },
                                {
                                  "type": "null"
                                }
                              ],
                              "description": "Unique identifier for the entity, can be null on create if auto-generated"
                            },
                            "productId": {
                              "type": "string",
                              "description": "References the product assigned to the category"
                            },
                            "activeFromDate": {
                              "type": "string",
                              "description": "Date from when the product is active in the category",
                              "format": "date"
                            },
                            "activeToDate": {
                              "anyOf": [
                                {
                                  "type": "string",
                                  "format": "date"
                                },
                                {
                                  "type": "null"
                                }
                              ],
                              "description": "Date to when the product is active in the category"
                            },
                            "auditInfo": {
                              "type": "object",
                              "description": "Audit information for the entity",
                              "additionalProperties": true,
                              "required": [
                                "createdBy",
                                "isDeleted",
                                "updatedBy",
                                "updatedDate",
                                "createdDate"
                              ],
                              "properties": {
                                "createdDate": {
                                  "anyOf": [
                                    {
                                      "type": "string",
                                      "format": "date-time"
                                    },
                                    {
                                      "type": "null"
                                    }
                                  ],
                                  "description": "Timestamp of when the entity was created"
                                },
                                "createdBy": {
                                  "type": "string",
                                  "description": "Identifies the system or user which created the entity"
                                },
                                "updatedDate": {
                                  "anyOf": [
                                    {
                                      "type": "string",
                                      "format": "date-time"
                                    },
                                    {
                                      "type": "null"
                                    }
                                  ],
                                  "description": "Timestamp of when the entity was last updated"
                                },
                                "updatedBy": {
                                  "type": "string",
                                  "description": "Identifies the system or user which last updated the entity"
                                },
                                "isDeleted": {
                                  "anyOf": [
                                    {
                                      "type": "boolean"
                                    },
                                    {
                                      "type": "null"
                                    }
                                  ],
                                  "description": "Indicates whether or not the entity has been soft-deleted"
                                }
                              }
                            }
                          }
                        }
                      ]
                    }
                  },
                  "auditInfo": {
                    "type": "object",
                    "description": "Audit information for the entity",
                    "additionalProperties": true,
                    "required": [
                      "createdBy",
                      "isDeleted",
                      "updatedBy",
                      "updatedDate",
                      "createdDate"
                    ],
                    "properties": {
                      "createdDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was created"
                      },
                      "createdBy": {
                        "type": "string",
                        "description": "Identifies the system or user which created the entity"
                      },
                      "updatedDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was last updated"
                      },
                      "updatedBy": {
                        "type": "string",
                        "description": "Identifies the system or user which last updated the entity"
                      },
                      "isDeleted": {
                        "anyOf": [
                          {
                            "type": "boolean"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Indicates whether or not the entity has been soft-deleted"
                      }
                    }
                  }
                }
              }
            ]
          }
        },
        "auditInfo": {
          "type": "object",
          "description": "Audit information for the entity",
          "additionalProperties": true,
          "required": [
            "createdBy",
            "isDeleted",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-produce-library/2.0.8/examples/ProductCatalogExample.json
{
  "id": "37dk0df9-11gl-33cz-p781-1242ac167762",
  "name": "Apparel",
  "activeFromDate": "2022-01-04",
  "activeToDate": "2022-10-07",
  "productCategories": [
    "021a697e-1865-4d8c-a9ab-9f0e575a847d"
  ],
  "auditInfo": {
    "createdDate": "2021-12-12T19:24:05Z",
    "createdBy": "Application Admin",
    "updatedDate": "2021-12-12T19:24:05Z",
    "updatedBy": "Application Admin",
    "isDeleted": false
  }
}
