=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-produce-library/2.0.8/jsonSchemas/ProductImageSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ProductImage",
  "definitions": {
    "ProductImage": {
      "description": "Represents an image associated with a product",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "id",
        "imageId"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "Unique identifier for the entity, can be null on create if auto-generated"
        },
        "imageId": {
          "type": "string",
          "description": "Reference to the actual image definition"
        },
        "imageGroupId": {
          "type": "string",
          "description": "Reference to the image group"
        },
        "imageViewType": {
          "type": "string",
          "description": "Classification of the image view, such as Large or Small icon"
        },
        "isDefaultImage": {
          "anyOf": [
            {
              "type": "boolean"
            },
            {
              "type": "null"
            }
          ],
          "description": "True if the image is the default one for the product, false otherwise"
        },
        "auditInfo": {
          "type": "object",
          "description": "Audit information for the entity",
          "additionalProperties": true,
          "required": [
            "createdBy",
            "isDeleted",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-produce-library/2.0.8/examples/ProductImageExample.json
{
  "id": "672f0064-bfcc-46c2-a336-2775d9906f0a",
  "imageId": "09895999-e987-4048-8a0f-59d52f8a6cdd",
  "imageGroupId": "",
  "imageViewType": "Small",
  "isDefaultImage": true,
  "auditInfo": {
    "createdDate": "2023-12-12T19:24:05Z",
    "createdBy": "Application Admin",
    "updatedDate": "2023-12-12T19:24:05Z",
    "updatedBy": "Application Admin",
    "isDeleted": true
  }
}
