=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-produce-library/2.0.8/jsonSchemas/PurchaseOrderProductSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/PurchaseOrderProduct",
  "definitions": {
    "PurchaseOrderProduct": {
      "description": "A shippable product or service that is part of a purchase order",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "id",
        "orderedQuantity",
        "unitPrice"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "Unique identifier for the entity, can be null on create if auto-generated"
        },
        "name": {
          "type": "string",
          "description": "Display name of the purchase order product"
        },
        "description": {
          "type": "string",
          "description": "Description of the purchase order product"
        },
        "lineNumber": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "description": "Line number of the purchase order product in a purchase order"
        },
        "productCode": {
          "type": "string",
          "description": "Supplier code of the product to be purchased"
        },
        "productName": {
          "type": "string",
          "description": "Name of the product, can be used if the supplier code is not known"
        },
        "orderedQuantity": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "description": "Number of product units requested"
        },
        "quantityUnitOfMeasure": {
          "type": "string",
          "description": "Unit of measure for the quantity requested"
        },
        "unitPrice": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "description": "Price per unit of product"
        },
        "requestedStartDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ],
          "description": "Date when the seller expects the provisioning of the service or product to begin"
        },
        "requestedEndDate": {
          "anyOf": [
            {
              "type": "string",
              "format": "date"
            },
            {
              "type": "null"
            }
          ],
          "description": "Date when the seller expects the provisioning of the service or product to end"
        },
        "productDeliveryLocation": {
          "type": "object",
          "description": "Identifies the location and address the product is to be shipped to",
          "additionalProperties": true,
          "required": [
            "id"
          ],
          "properties": {
            "id": {
              "anyOf": [
                {
                  "type": "string"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Unique identifier for the entity, can be null on create if auto-generated"
            },
            "name": {
              "type": "string",
              "description": "Display name of the location"
            },
            "contactName": {
              "type": "string",
              "description": "Name of the person to contact at this location (for receiving shipments, as an example)"
            },
            "locationCode": {
              "type": "string",
              "description": "Alternate code associated with the location"
            },
            "locationType": {
              "type": "string",
              "description": "Reference to the type of location (for example, Bulding, Ship, Arena)"
            },
            "locationAddress": {
              "type": "object",
              "description": "Free-form or structured address of the location",
              "additionalProperties": true,
              "required": [
                "addressLine1"
              ],
              "properties": {
                "name": {
                  "type": "string",
                  "description": "Optional display name for the address"
                },
                "addressLine1": {
                  "type": "string",
                  "description": "The first address line can be used by itself for unstructured addresses"
                },
                "addressLine2": {
                  "type": "string",
                  "description": "Optional second line of the address"
                },
                "addressLine3": {
                  "type": "string",
                  "description": "Optional third line of the address"
                },
                "cityName": {
                  "type": "string",
                  "description": "Display name of the city for the address"
                },
                "stateProvinceName": {
                  "type": "string",
                  "description": "Display name of the state or province for the address"
                },
                "stateProvinceCode": {
                  "type": "string",
                  "description": "The ISO region code for the address"
                },
                "countryName": {
                  "type": "string",
                  "description": "Display name of the country for the address"
                },
                "countryCode": {
                  "type": "string",
                  "description": "The ISO country code for the address"
                },
                "postalCodeText": {
                  "type": "string",
                  "description": "The postal code for the address"
                },
                "geoAccuracyCode": {
                  "type": "string",
                  "description": "Provides more information about the latitude and longitude of the address"
                },
                "geoLatitude": {
                  "anyOf": [
                    {
                      "type": "number"
                    },
                    {
                      "type": "null"
                    }
                  ],
                  "description": "The latitude of the address"
                },
                "geoLongitude": {
                  "anyOf": [
                    {
                      "type": "number"
                    },
                    {
                      "type": "null"
                    }
                  ],
                  "description": "The longitude of the address"
                }
              }
            },
            "auditInfo": {
              "type": "object",
              "description": "Audit information for the entity",
              "additionalProperties": true,
              "required": [
                "isDeleted",
                "createdBy",
                "updatedBy",
                "updatedDate",
                "createdDate"
              ],
              "properties": {
                "createdDate": {
                  "anyOf": [
                    {
                      "type": "string",
                      "format": "date-time"
                    },
                    {
                      "type": "null"
                    }
                  ],
                  "description": "Timestamp of when the entity was created"
                },
                "createdBy": {
                  "type": "string",
                  "description": "Identifies the system or user which created the entity"
                },
                "updatedDate": {
                  "anyOf": [
                    {
                      "type": "string",
                      "format": "date-time"
                    },
                    {
                      "type": "null"
                    }
                  ],
                  "description": "Timestamp of when the entity was last updated"
                },
                "updatedBy": {
                  "type": "string",
                  "description": "Identifies the system or user which last updated the entity"
                },
                "isDeleted": {
                  "anyOf": [
                    {
                      "type": "boolean"
                    },
                    {
                      "type": "null"
                    }
                  ],
                  "description": "Indicates whether or not the entity has been soft-deleted"
                }
              }
            }
          }
        },
        "auditInfo": {
          "type": "object",
          "description": "Audit information for the entity",
          "additionalProperties": true,
          "required": [
            "createdBy",
            "isDeleted",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-produce-library/2.0.8/examples/PurchaseOrderProductExample.json
{
  "id": "66815379-cdaf-4883-b05a-fd726426fdcf",
  "name": "Printer Paper",
  "description": "8.5\" x 11\" Copy Paper, 20 lbs, 92 Brightness, 5000/Carton (324791)",
  "lineNumber": 1,
  "productCode": "Tuna-181",
  "productName": "Handcrafted Frozen Tuna",
  "orderedQuantity": 20.0,
  "quantityUnitOfMeasure": "case",
  "unitPrice": 34.45,
  "requestedStartDate": null,
  "requestedEndDate": null,
  "productDeliveryLocation": {
    "id": null,
    "name": "Customer Address",
    "contactName": "Samuel L. Smith",
    "locationCode": "338",
    "locationAddress": {
      "addressLine1": "2122 Maple Street",
      "addressLine2": "Unit 23",
      "addressLine3": "",
      "cityName": "Austin",
      "stateProvinceCode": "TX",
      "countryCode": "US",
      "postalCodeText": "45145"
    }
  },
  "auditInfo": {
    "createdBy": "Application Admin",
    "createdDate": "2023-12-12T19:24:05Z",
    "updatedBy": "Application Admin",
    "updatedDate": "2023-12-12T19:24:05Z",
    "isDeleted": false
  }
}
