=== SamuelSumamoos/apicuentasfragments/exchange_modules/org.mule.templates/accel-b2b-common-library/1.0.10/jsonSchemas/OrderStatusChangedEventSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/OrderStatusChangedEvent",
  "definitions": {
    "OrderStatusChangedEvent": {
      "discriminator": "orderEventType",
      "description": "Represents a change in the status of an order.",
      "type": "object",
      "discriminatorValue": "OrderStatusChangedEvent",
      "additionalProperties": true,
      "required": [
        "orderEventType",
        "newOrderStatus",
        "orderId",
        "id",
        "oldOrderStatus"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "Unique identifier for the entity, can be null on create if auto-generated"
        },
        "orderEventType": {
          "type": "string",
          "description": "Discriminator identifying the specific type of event instance (for example, OrderStatusEvent)"
        },
        "auditInfo": {
          "type": "object",
          "description": "Defines standard system audit fields available for most types",
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        },
        "orderId": {
          "type": "string",
          "description": "Identifies the order that produced this event"
        },
        "oldOrderStatus": {
          "type": "string",
          "description": "Previous order status value"
        },
        "newOrderStatus": {
          "type": "string",
          "description": "Current order status value"
        }
      }
    }
  }
}

=== SamuelSumamoos/apicuentasfragments/exchange_modules/org.mule.templates/accel-b2b-common-library/1.0.10/examples/OrderStatusChangedEventExample.json
{
  "id": "af3d5c80-f237-11ec-9d38-02b65bc9fbca",
  "orderEventType": "OrderStatusChangedEvent",
  "orderId": "27be8a1a-fe13-4ca1-9c6b-2c8da76004f8",
  "oldOrderStatus": "Created",
  "newOrderStatus": "Allocated",
  "auditInfo": {
    "createdDate": "2024-02-15T15:03:01Z",
    "createdBy": "Administrator",
    "updatedDate": "2024-02-15T15:03:01Z",
    "updatedBy": "Administrator",
    "isDeleted": false
  }
}
