=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org.mule.templates/accel-b2b-common-library/1.0.10/jsonSchemas/OrderCreatedEventSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/OrderCreatedEvent",
  "definitions": {
    "OrderCreatedEvent": {
      "discriminator": "orderEventType",
      "description": "Represents an order that has been created by the order management system",
      "type": "object",
      "discriminatorValue": "OrderCreatedEvent",
      "additionalProperties": true,
      "required": [
        "orderEventType",
        "id",
        "purchaseOrderNumber",
        "purchaseOrderDate"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "Unique identifier for the entity, can be null on create if auto-generated"
        },
        "orderEventType": {
          "type": "string",
          "description": "Discriminator identifying the specific type of event instance (for example, OrderStatusEvent)"
        },
        "auditInfo": {
          "type": "object",
          "description": "Defines standard system audit fields available for most types",
          "additionalProperties": true,
          "required": [
            "isDeleted",
            "createdBy",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        },
        "purchaseOrderNumber": {
          "type": "string",
          "description": "References the original purchase order"
        },
        "purchaseOrderDate": {
          "type": "string",
          "description": "Date the purchase order was created",
          "format": "date"
        },
        "purchasingOrganizationCode": {
          "type": "string",
          "description": "B2B code identifying the organization that submitted the purchase order"
        }
      }
    }
  }
}

=== SamuelSumamoos/apicuentasfragments/exchange_modules/org.mule.templates/accel-b2b-common-library/1.0.10/examples/OrderCreatedEventExample.json
{
  "id": "af3d5c80-f237-11ec-9d38-02b65bc9fbca",
  "orderEventType": "OrderCreatedEvent",
  "purchaseOrderNumber": "ORD-02338301",
  "purchaseOrderDate": "2024-03-02",
  "purchasingOrganizationCode": "ORANGE",
  "auditInfo": {
    "createdDate": "2024-02-15T15:03:01Z",
    "createdBy": "autoproc",
    "updatedDate": "2024-02-15T15:03:01Z",
    "updatedBy": "autoproc",
    "isDeleted": false
  }
}
