=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-fulfill-library/2.0.5/jsonSchemas/ShipmentDocumentSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ShipmentDocument",
  "definitions": {
    "ShipmentDocument": {
      "description": "A receipt, bill of lading or other document that is delivered with the shipment to explain the purchase or shipment contents",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "Unique identifier for the entity, can be null on create if auto-generated"
        },
        "contentDocumentVersion": {
          "type": "string",
          "description": "References the version of the document to be included"
        },
        "shipmentPackageId": {
          "type": "string",
          "description": "References the package to which the document applies"
        },
        "auditInfo": {
          "type": "object",
          "description": "Audit information for the entity",
          "additionalProperties": true,
          "required": [
            "createdBy",
            "isDeleted",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-fulfill-library/2.0.5/examples/ShipmentDocumentExample.json
{
  "id": "01a8c013-70af-4272-9dbb-bf9f86b2bcd5",
  "contentDocumentVersion": "1.0",
  "shipmentPackageId": "b9d3552d-f95a-4658-8f44-9d9c20a858de",
  "auditInfo": {
    "createdDate": "2021-12-12T19:24:05Z",
    "createdBy": "Application Admin",
    "updatedDate": "2021-12-12T19:24:05Z",
    "updatedBy": "Application Admin",
    "isDeleted": false
  }
}
