=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-fulfill-library/2.0.5/jsonSchemas/ShipmentPackageSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ShipmentPackage",
  "definitions": {
    "ShipmentPackage": {
      "description": "A parcel of one or more items bundled together, so that they arrive at the location as a single unit",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "Unique identifier for the entity, can be null on create if auto-generated"
        },
        "description": {
          "type": "string",
          "description": "Description of the package"
        },
        "shipmentProductCount": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "description": "How many individual products are included in the package"
        },
        "auditInfo": {
          "type": "object",
          "description": "Audit information for the entity",
          "additionalProperties": true,
          "required": [
            "createdBy",
            "isDeleted",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-fulfill-library/2.0.5/examples/ShipmentPackageExample.json
{
  "id": "b9d3552d-f95a-4658-8f44-9d9c20a858de",
  "description": "Box of tennis shoes",
  "shipmentProductCount": 10,
  "auditInfo": {
    "createdDate": "2021-12-12T19:24:05Z",
    "createdBy": "Application Admin",
    "updatedDate": "2021-12-12T19:24:05Z",
    "updatedBy": "Application Admin",
    "isDeleted": false
  }
}
