=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-fulfill-library/2.0.5/jsonSchemas/ShipmentProductSchema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/ShipmentProduct",
  "definitions": {
    "ShipmentProduct": {
      "description": "An item on a list of one or more that comprises a shipment",
      "type": "object",
      "additionalProperties": true,
      "required": [
        "id"
      ],
      "properties": {
        "id": {
          "anyOf": [
            {
              "type": "string"
            },
            {
              "type": "null"
            }
          ],
          "description": "Unique identifier for the entity, can be null on create if auto-generated"
        },
        "lineNumber": {
          "anyOf": [
            {
              "type": "integer"
            },
            {
              "type": "null"
            }
          ],
          "description": "Line number of the shipment product in a shipment"
        },
        "productCode": {
          "type": "string",
          "description": "References the actual product to be shipped"
        },
        "fulfillmentOrderId": {
          "type": "string",
          "description": "Identifier of the fulfillment order that originated the request for shipment, if the shipment includes products for multiple orders"
        },
        "fulfillmentOrderProductId": {
          "type": "string",
          "description": "References the product line item from the associated fulfillment order"
        },
        "salesOrderId": {
          "type": "string",
          "description": "Identifier of the original sales order that originated the request for fulfillment, if the shipment includes products for multiple orders"
        },
        "salesOrderProductId": {
          "type": "string",
          "description": "References the product line item from the original sales order"
        },
        "shipmentPackageId": {
          "type": "string",
          "description": "References the package in which the item was packed"
        },
        "quantity": {
          "anyOf": [
            {
              "type": "number"
            },
            {
              "type": "null"
            }
          ],
          "description": "How many instances of the product are to be shipped"
        },
        "priceAdjustments": {
          "type": "array",
          "description": "List of price adjustments for the shipment product, which can be a list of identifier references or complete objects (not both)",
          "items": {
            "anyOf": [
              {
                "type": "string"
              },
              {
                "description": "A change to the price of an ordered product or service that is made after fulfillment.",
                "type": "object",
                "additionalProperties": true,
                "required": [
                  "id",
                  "adjustmentAmount"
                ],
                "properties": {
                  "id": {
                    "anyOf": [
                      {
                        "type": "string"
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "description": "Unique identifier for the entity, can be null on create if auto-generated"
                  },
                  "description": {
                    "type": "string",
                    "description": "Description of the shipment product price adjustment"
                  },
                  "adjustmentAmount": {
                    "type": "number",
                    "description": "Adjustment amount for the shipment product"
                  },
                  "adjustmentTaxAmount": {
                    "anyOf": [
                      {
                        "type": "number"
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "description": "Tax on the adjustment amount"
                  },
                  "adjustmentAmountWithTax": {
                    "anyOf": [
                      {
                        "type": "number"
                      },
                      {
                        "type": "null"
                      }
                    ],
                    "description": "Sum of adjustmentAmount + adjustmentTaxAmount"
                  },
                  "auditInfo": {
                    "type": "object",
                    "description": "Audit information for the entity",
                    "additionalProperties": true,
                    "required": [
                      "createdBy",
                      "isDeleted",
                      "updatedBy",
                      "updatedDate",
                      "createdDate"
                    ],
                    "properties": {
                      "createdDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was created"
                      },
                      "createdBy": {
                        "type": "string",
                        "description": "Identifies the system or user which created the entity"
                      },
                      "updatedDate": {
                        "anyOf": [
                          {
                            "type": "string",
                            "format": "date-time"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Timestamp of when the entity was last updated"
                      },
                      "updatedBy": {
                        "type": "string",
                        "description": "Identifies the system or user which last updated the entity"
                      },
                      "isDeleted": {
                        "anyOf": [
                          {
                            "type": "boolean"
                          },
                          {
                            "type": "null"
                          }
                        ],
                        "description": "Indicates whether or not the entity has been soft-deleted"
                      }
                    }
                  }
                }
              }
            ]
          }
        },
        "auditInfo": {
          "type": "object",
          "description": "Audit information for the entity",
          "additionalProperties": true,
          "required": [
            "createdBy",
            "isDeleted",
            "updatedBy",
            "updatedDate",
            "createdDate"
          ],
          "properties": {
            "createdDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was created"
            },
            "createdBy": {
              "type": "string",
              "description": "Identifies the system or user which created the entity"
            },
            "updatedDate": {
              "anyOf": [
                {
                  "type": "string",
                  "format": "date-time"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Timestamp of when the entity was last updated"
            },
            "updatedBy": {
              "type": "string",
              "description": "Identifies the system or user which last updated the entity"
            },
            "isDeleted": {
              "anyOf": [
                {
                  "type": "boolean"
                },
                {
                  "type": "null"
                }
              ],
              "description": "Indicates whether or not the entity has been soft-deleted"
            }
          }
        }
      }
    }
  }
}

=== SamuelSumamoos/apicuentasfragments/.exchange_modules_tmp/target/full_api/exchange_modules/org/mule/templates/accelerator-cim-fulfill-library/2.0.5/examples/ShipmentProductExample.json
{
  "id": "13814c11-5397-4779-ac8b-dd692af251c2",
  "lineNumber": 1,
  "productCode": "MachineParts-X50",
  "fulfillmentOrderId": "",
  "fulfillmentOrderProductId": "3b2560f4-b84f-4c98-9783-2a1ed164ef00",
  "salesOrderId": "",
  "salesOrderProductId": "8e931313-1a1d-4284-9b81-c14c6f1c0387",
  "shipmentPackageId": "b9d3552d-f95a-4658-8f44-9d9c20a858de",
  "quantity": 15.0,
  "priceAdjustments": [
    {
      "id": null,
      "description": "Repeat customer discount",
      "adjustmentAmount": 50.0,
      "adjustmentTaxAmount": 7.0,
      "adjustmentAmountWithTax": 57.0
    }
  ],
  "auditInfo": {
    "createdDate": "2021-12-12T19:24:05Z",
    "createdBy": "Application Admin",
    "updatedDate": "2021-12-12T19:24:05Z",
    "updatedBy": "Application Admin",
    "isDeleted": false
  }
}
